version: '2'
services:
  get_stream:
    build: getstream
    container_name: get_stream
    volumes:
      - "./get_stream/app:/usr/src/app"
    working_dir: "/usr/src/app"
    environment:
      MASTODON_HOST: $MASTODON_HOST 
      CLIENT_NAME: $CLIENT_NAME 
      CLIENT_ID: $CLIENT_ID 
      CLIENT_SECRET: $CLIENT_SECRET 
      ACCESS_TOKEN: $ACCESS_TOKEN 
    tty: true
    restart: always