version: '2'
services:
  app_data:
    image: busybox
    container_name: app_data
    volumes:
      - "./app:/usr/src/app"
  INTAKE:
    build: INTAKE
    image: intake
    container_name: INTAKE
    working_dir: "/usr/src/app"
    volumes_from:
      - app_data
    environment:
      CLIENT_MAME: $CLIENT_NAME
      MASTODON_USER: $MASTODON_USER
      MASTODON_PASS: $MASTODON_PASS
      API_BASE_URL: $API_BASE_URL
      DATABASE_URL: $DATABASE_URL
    command: python intake.py
    tty: true
    restart: always

  INTAKE2:
    build: INTAKE
    image: intake
    container_name: INTAKE2
    working_dir: "/usr/src/app"
    volumes_from:
      - app_data
    environment:
      CLIENT_MAME: $CLIENT_NAME
      MASTODON_USER: $MASTODON_USER
      MASTODON_PASS: $MASTODON_PASS
      API_BASE_URL: $API_BASE_URL
      DATABASE_URL: $DATABASE_URL
    command: python intake.py
    tty: true
    restart: always
  
  BUCKET_data:
    image: busybox
    container_name: BUCKET_data
    volumes:
      - "./BUCKET/postgres_data:/var/lib/postgresql"

  BUCKET:
    build: BUCKET
    image: bucket
    container_name: BUCKET
    ports:
      - "5432:5432"
    # volumes_from:
    #   - BUCKET_data
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    restart: always