version: '2'
services:
  db_data:
    image: busybox
    container_name: db_data
    volumes:
      - ./db_data
  db:
    image: postgres
    container_name: db
    volumes_from:
      - db_data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASS: p0stgres!
networks:
  ext_nw:
    external: true
  int_nw: