version: '2'
services:
  get_stream:
    build: get_stream
    container_name: get_stream
    volumes:
      - "./get_stream/app:/usr/src/app"
      #- "/var/run/docker.sock:/var/run/docker.sock"
      #- "/usr/bin/docker:/usr/bin/docker"
    working_dir: "/usr/src/app"
    environment:
      MASTODON_HOST: $MASTODON_HOST 
      CLIENT_NAME: $CLIENT_NAME 
      CLIENT_ID: $CLIENT_ID 
      CLIENT_SECRET: $CLIENT_SECRET 
      ACCESS_TOKEN: $ACCESS_TOKEN 
    command: python main.py
    tty: true
    restart: always