version: '2'
services:
  get_stream:
    build: get_stream
    container_name: get_stream
    volumes:
      - "./get_stream/app:/usr/src/app"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/bin/docker:/usr/bin/docker"
    working_dir: "/usr/src/app"
    environment:
      CLIENT_MAME: $CLIENT_NAME
      MASTODON_USER: $MASTODON_USER
      MASTODON_PASS: $MASTODON_PASS
      API_BASE_URL: $API_BASE_URL
    command: python main.py
    tty: true
    restart: always